In [46]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [47]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [21]:
#cleaning the text

import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
ps=PorterStemmer()
wordnet=WordNetLemmatizer()
nltk.download('wordnet')
sentences=nltk.sent_tokenize(paragraph)

corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[i])
    #replace characters other than [a-z] and (A-Z) with spaces
    review=review.lower()#convert tolowercase
    review=review.split()# split using space(list of words)
    review=[wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    #check whether stop word  or not
    review=' '.join(review)# join the preprocessed words
    corpus.append(review)# append the content

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [22]:
corpus

['three vision india',
 'year history people world come invaded u captured land conquered mind',
 'alexander onwards greek turk mogul portuguese british french dutch came looted u took',
 'yet done nation',
 'conquered anyone',
 'grabbed land culture history tried enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india got first vision started war independence',
 'freedom must protect nurture build',
 'free one respect u',
 'second vision india development',
 'fifty year developing nation',
 'time see developed nation',
 'among top nation world term gdp',
 'percent growth rate area',
 'poverty level falling',
 'achievement globally recognised today',
 'yet lack self confidence see developed nation self reliant self assured',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect u',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune worked three great mind',
 'dr vikram sarabhai dept',
 'space professor satish dhawan succeeded dr brahm prakash father nuclear material',
 'lucky worked three closely consider great opportunity life',
 'see four milestone career']

In [23]:
# creating the TF IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()

In [24]:
x=tf.fit_transform(corpus).toarray()

In [25]:
x

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.25883507, 0.30512561,
        0.        ],
       [0.        , 0.28867513, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [26]:
x.shape

(31, 114)

## F train data

In [27]:
import pandas as pd
import numpy as np

In [28]:
data=pd.read_csv('f_train.csv')
data

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1

In [37]:
x=data.iloc[:500]
x

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...,...
495,495,Contaminated Food from China Now Entering the ...,noreply@blogger.com (Alexander Light),Contaminated Food from China Now Entering the ...,1
496,496,Ten Famous People on What to Read This Summer ...,T Magazine,"For his bookshop and website One Grand Books, ...",0
497,497,SCANDAL: EPA could have issued an emergency or...,NaN,SCANDAL: EPA could have issued an emergency or...,1
498,498,Hillary Clinton KNEW 5 years ago Anthony Weine...,The European Union Times,\nA WikiLeak’s email released on Monday reveal...,1
499,499,أوروبا وخيار القوة في مواجهة اللاجئين - RT Arabic,NaN,أوروبا وخيار القوة في مواجهة اللاجئين \nتاريخ ...,1

In [38]:
x.isnull().sum()

id         0
title      8
author    60
text       1
label      0
dtype: int64

In [39]:
x=x.dropna()
x

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...,...
493,493,Police fire rubber bullets at pipeline protesters,Alex Ansary,Police fire rubber bullets at pipeline protest...,1
494,494,Ann Coulter Hits Supposed ’Gay Icon’ Kathy Gri...,Ian Mason,Conservative columnist and bestselling author ...,0
495,495,Contaminated Food from China Now Entering the ...,noreply@blogger.com (Alexander Light),Contaminated Food from China Now Entering the ...,1
496,496,Ten Famous People on What to Read This Summer ...,T Magazine,"For his bookshop and website One Grand Books, ...",0
498,498,Hillary Clinton KNEW 5 years ago Anthony Weine...,The European Union Times,\nA WikiLeak’s email released on Monday reveal...,1

In [40]:
x.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [41]:
x=x.reset_index()
x

,index,id,title,author,text,label
0,0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...,...,...
427,493,493,Police fire rubber bullets at pipeline protesters,Alex Ansary,Police fire rubber bullets at pipeline protest...,1
428,494,494,Ann Coulter Hits Supposed ’Gay Icon’ Kathy Gri...,Ian Mason,Conservative columnist and bestselling author ...,0
429,495,495,Contaminated Food from China Now Entering the ...,noreply@blogger.com (Alexander Light),Contaminated Food from China Now Entering the ...,1
430,496,496,Ten Famous People on What to Read This Summer ...,T Magazine,"For his bookshop and website One Grand Books, ...",0
431,498,498,Hillary Clinton KNEW 5 years ago Anthony Weine...,The European Union Times,\nA WikiLeak’s email released on Monday reveal...,1

In [42]:
len(x)

432

In [43]:
import re
import nltk
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.stem import PorterStemmer
ps=PorterStemmer()
from nltk.stem import WordNetLemmatizer
wl=WordNetLemmatizer()

In [ ]:
#data cleaning and preprocessing
corpus=[]
for i in range(0,len(x)):
    review=re.sub('[^a-zA-Z]',' ',x['text'][i])
    
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    
    review=' '.join(review)
    corpus.append(review)

In [48]:
l1=[]
for i in range(0,len(data)):
    review=re.sub('[^a-zA-Z]',' ',x['text'][i])
    review=review.lower()
    review=review.split() 
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review) 
    l1.append(review)

KeyError: 432